import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";

const vazirmatn = Vazirmatn({
  subsets: ["latin", "arabic"],
  weight: ["200"],
  variable: "--font-vazirmatn",
});

export const metadata: Metadata = {
  title: "آرایشگاه امیر محمد",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html dir="rtl" lang="fa">
      <body className={`${vazirmatn.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
