import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const vazirmatn = Vazirmatn({
  subsets: ["latin", "arabic"],
  weight: ["200"],
  variable: "--font-vazirmatn",
});

export const metadata: Metadata = {
  title: "آرایشگاه امیر محمد",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <Toaster
        position="top-center"
        toastOptions={{
          style: {
            boxShadow: "none", // حذف سایه کامل
          },
        }}
      />
      <html className="w-full" dir="rtl" lang="fa">
        <body className={`${vazirmatn.className} antialiased`}>{children}</body>
      </html>
    </>
  );
}
